# Generated by Django 5.2.8 on 2025-11-18 12:10

import catalog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_category_alter_user_date_of_birth_application'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='image',
            field=models.ImageField(upload_to='applications/', validators=[catalog.models.validate_image]),
        ),
    ]
